- name: Task for web and db
  hosts: lamp
  tasks:
    - include_tasks: setup-nginx.yml
      when: vps_webserver == 'nginx'
    - include_tasks: setup-apache2.yml
      when: vps_webserver == 'apache2'
    - include_tasks: setup-php.yml
    - include_tasks: setup-mariadb.yml
    - include_tasks: setup-wp-cli.yml
    - include_tasks: setup-wordpress.yml

    - name: validate apache2 configuration and restart apache2
      command: /usr/sbin/apachectl configtest

    - name: restart apache2
      service: name=apache2 state=restarted