- name: add php repository
  apt_repository:
    repo: ppa:ondrej/php

- name: install php {{ vps_php_version }}
  apt:
    name:
      - php{{ vps_php_version }}
      - php{{ vps_php_version }}-curl
      - php{{ vps_php_version }}-gd
      - php{{ vps_php_version }}-mbstring
      - php{{ vps_php_version }}-xml
      - php{{ vps_php_version }}-xmlrpc
      - php{{ vps_php_version }}-soap
      - php{{ vps_php_version }}-intl
      - php{{ vps_php_version }}-zip
      - php{{ vps_php_version }}-mysql
    state: present
    
- name: install php additional mods
  apt:
    name: php{{ vps_php_version }}-{{ item }}
  loop: "{{ vps_php_additional_mods }}"
  
- name: install php fpm for nginx
  apt:
    name: php{{ vps_php_version }}-fpm
  when: vps_webserver == 'nginx'

- name: install libmodphp fpm for apache
  apt:
    name: libapache2-mod-php{{ vps_php_version }}
  when: vps_webserver == 'apache'