- name: install MariaDB
  apt:
    name:
      - mariadb-server
      - mariadb-client
      - python3-mysqldb
      - libmysqlclient-dev

# Tworzenie usera i bazy
- name: create a database
  community.mysql.mysql_db:
    name: "{{ item.db_name }}"
    state: present
  when: item.state|default('present') != 'absent'
  loop: "{{ vps_vhosts }}"

- name: create users and priv
  community.mysql.mysql_user:
    name: "{{ item.db_username }}"
    password: "{{ item.db_password }}"
    priv: "{{ item.db_name }}.*:ALL"
    state: present
  when: item.state|default('present') != 'absent'
  loop: "{{ vps_vhosts }}"

# usuwanie usera i bazy
- name: cleanup database
  community.mysql.mysql_db:
    name: "{{ item.db_name }}"
    state: absent
  when: item.state|default('present') == 'absent'
  loop: "{{ vps_vhosts }}"

- name: cleanup users and priv
  community.mysql.mysql_user:
    name: "{{ item.db_username }}"
    password: "{{ item.db_password }}"
    priv: "{{ item.db_name }}.*:ALL"
    state: absent
  when: item.state|default('present') == 'absent'
  loop: "{{ vps_vhosts }}"