# tworzenie katalogów na strony
- name: Create a directory if it does not exist
  file:
    path: "/var/www/{{ item.server_name }}"
    state: directory
    mode: '0755'
  when: item.state|default('present') != 'absent'
  loop: "{{ vps_vhosts }}"

# usuwanie katalogów z WordPressami przeznaczonych do usunięcia
- name: cleanup a directory if it does not exist
  file:
    path: "/var/www/{{ item.server_name }}"
    state: absent
  when: item.state|default('present') == 'absent'
  loop: "{{ vps_vhosts }}"

# czy WordPress jest już zainstalowany w tym katalogu?
- name: check if wp is installed
  stat:
    path: /var/www/{{ item.server_name }}/index.php
  register: is_wordpress_installed
  when: item.state|default('present') != 'absent'
  loop: "{{ vps_vhosts }}"

# ściągnięcie instalatora WordPressa z użyciem wp-cli
- name: download wp core
  command: "{{ vps_wp_cli_path }} core download --path=/var/www/{{ item.item.server_name }} --allow-root"
  when: item.stat.exists is defined and item.stat.exists == False and item.item.state|default('present') != 'absent'
  loop: "{{ is_wordpress_installed.results }}"

# konfiguracja WordPressa (loginy, hasła itp.)
- name: wp config
  command: "{{ vps_wp_cli_path }} core config --dbhost=localhost --dbname={{ item.item.db_name }} --dbuser={{ item.item.db_username }} --dbpass={{ item.item.db_password }} --path=/var/www/{{ item.item.server_name}} --allow-root"
  when: item.stat.exists is defined and item.stat.exists == False and item.item.state|default('present') != 'absent'
  loop: "{{ is_wordpress_installed.results }}"

# rozpoczęcie instlacji WordPressa
- name: wp install
  command: '{{ vps_wp_cli_path }} core install --url={{ item.item.server_name }} --title="{{ item.item.wp_title }}" --admin_name={{ item.item.wp_admin }} --admin_password={{ item.item.wp_admin_password }} --admin_email={{ item.item.wp_admin_email }} --path=/var/www/{{ item.item.server_name }} --allow-root'
  when: item.stat.exists is defined and item.stat.exists == False and item.item.state|default('present') != 'absent'
  loop: "{{ is_wordpress_installed.results }}"

# zmiana praw dostępu do katalogu wp-content
- name: Change wp-content permissions
  file:
    path: /var/www/{{ item.item.server_name }}/wp-content
    owner: www-data
    group: www-data
    recurse: true
    mode: '755'
  when: item.stat.exists is defined and item.stat.exists == False and item.item.state|default('present') != 'absent'
  loop: "{{ is_wordpress_installed.results }}"

# wersja dla apache2
- name: change php ini for apache2
  lineinfile:
    dest: /etc/php/{{ vps_php_version }}/apache2/php.ini
    regexp: "{{ item }} ="
    line: "{{ item }} = 128M"
  loop:
    - upload_max_filesize
    - post_max_size
  when: vps_webserver == 'apache2'
  # notify:
  #   - validate apache2 configuration and restart apache2