# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "ubuntu/trusty64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "./", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  
  config.vbguest.auto_update = true

  config.vm.define "pc-private" do |pcprivate|
    pcprivate.vm.box = "ubuntu/trusty64"
    pcprivate.vm.hostname = "pc-private"
    pcprivate.vm.network "private_network", ip: "10.0.0.77", virtualbox__intnet: "private"
    pcprivate.vm.provision "shell", path: "./provision/pc-private.sh"
    pcprivate.vm.provider "virtualbox" do |vb|
      vb.name = "pc-private"
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
    end
  end

  config.vm.define "fw1" do |fw1|
    fw1.vm.box = "ubuntu/trusty64"
    fw1.vm.hostname = "fw1"
    fw1.vm.network "private_network", ip: "172.27.1.90", virtualbox__intnet: "public"
    fw1.vm.network "private_network", ip: "10.0.0.254", virtualbox__intnet: "private"
    fw1.vm.provision "shell", path: "./provision/fw1.sh"
    fw1.vm.provider "virtualbox" do |vb|
      vb.name = "fw1"
      vb.gui = false
      vb.cpus = 1
      vb.memory = "512"
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end
  end

  config.vm.define "pc-public" do |pcpublic|
    pcpublic.vm.box = "ubuntu/trusty64"
    pcpublic.vm.hostname = "pc-public"
    pcpublic.vm.network "public_network", bridge: "wlp5s0"
    pcpublic.vm.network "private_network", ip: "172.27.1.94", virtualbox__intnet: "public"
    pcpublic.vm.provision "shell", path: "./provision/pc-public.sh"
    pcpublic.vm.provider "virtualbox" do |vb|
      vb.name = "pc-public"
      vb.gui = false
      vb.cpus = 1
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
    end
  end
end
